apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: reloader
 namespace: argocd
spec:
 project: global-color-platform
 
 source:
   repoURL: https://github.com/kxn928/mosaic-argocd-helmfiles.git
   targetRevision: main
   path: sb-mosaic-aks/reloader
 destination:
   server: https://kubernetes.default.svc
   namespace: reloader

 syncPolicy:
   syncOptions:
   - CreateNamespace=true

   automated:
     selfHeal: true
     prune: true